[package]
name = "autosar-data"
version = "0.2.0"
authors = ["Daniel Thaler <daniel@dthaler.de>"]
edition = "2021"
description = "read, write and modify Autosar data"
license = "MIT OR Apache-2.0"
keywords = ["arxml", "file", "file-format", "Autosar"]
categories = ["parser-implementations"]
repository = "https://github.com/DanielT/autosar-data"

[dependencies]
autosar-data-specification = "0.2"
thiserror = "~1.0"
smallvec = { version = "~1.8.0", features = ["union", "const_generics"]}
parking_lot = "0.12"
rustc-hash = "1.1.0"

# [dev-dependencies]
# criterion = "0.3"

[[example]]
name = "demo"

# [[bench]]
# name = "parse_benchmark"
# harness = false
